
services:
  postgresql:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102104
      POSTGRES_DB: shop
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgresqlTest:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102104
      POSTGRES_DB: TestShop
    restart: unless-stopped
    
    ports:
      - "5433:5432"

  avito-shop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    env_file:
      - ./config/.env

volumes:
  postgres_data: