// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/service.go -package=mocks -source=service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "avito-shop/internal/entity"
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockitemRepository is a mock of itemRepository interface.
type MockitemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockitemRepositoryMockRecorder
	isgomock struct{}
}

// MockitemRepositoryMockRecorder is the mock recorder for MockitemRepository.
type MockitemRepositoryMockRecorder struct {
	mock *MockitemRepository
}

// NewMockitemRepository creates a new mock instance.
func NewMockitemRepository(ctrl *gomock.Controller) *MockitemRepository {
	mock := &MockitemRepository{ctrl: ctrl}
	mock.recorder = &MockitemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemRepository) EXPECT() *MockitemRepositoryMockRecorder {
	return m.recorder
}

// AddItemByUserId mocks base method.
func (m *MockitemRepository) AddItemByUserId(ctx context.Context, tx pgx.Tx, userID, item int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItemByUserId", ctx, tx, userID, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItemByUserId indicates an expected call of AddItemByUserId.
func (mr *MockitemRepositoryMockRecorder) AddItemByUserId(ctx, tx, userID, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItemByUserId", reflect.TypeOf((*MockitemRepository)(nil).AddItemByUserId), ctx, tx, userID, item)
}

// GetItemByName mocks base method.
func (m *MockitemRepository) GetItemByName(ctx context.Context, tx pgx.Tx, nameItem string) (*entity.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByName", ctx, tx, nameItem)
	ret0, _ := ret[0].(*entity.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByName indicates an expected call of GetItemByName.
func (mr *MockitemRepositoryMockRecorder) GetItemByName(ctx, tx, nameItem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByName", reflect.TypeOf((*MockitemRepository)(nil).GetItemByName), ctx, tx, nameItem)
}

// StartTransaction mocks base method.
func (m *MockitemRepository) StartTransaction(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockitemRepositoryMockRecorder) StartTransaction(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockitemRepository)(nil).StartTransaction), ctx)
}

// MockwalletRepository is a mock of walletRepository interface.
type MockwalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockwalletRepositoryMockRecorder
	isgomock struct{}
}

// MockwalletRepositoryMockRecorder is the mock recorder for MockwalletRepository.
type MockwalletRepositoryMockRecorder struct {
	mock *MockwalletRepository
}

// NewMockwalletRepository creates a new mock instance.
func NewMockwalletRepository(ctrl *gomock.Controller) *MockwalletRepository {
	mock := &MockwalletRepository{ctrl: ctrl}
	mock.recorder = &MockwalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwalletRepository) EXPECT() *MockwalletRepositoryMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockwalletRepository) CreateWallet(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockwalletRepositoryMockRecorder) CreateWallet(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockwalletRepository)(nil).CreateWallet), ctx, userID)
}

// GetAmountByUserId mocks base method.
func (m *MockwalletRepository) GetAmountByUserId(ctx context.Context, tx pgx.Tx, userID int) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAmountByUserId", ctx, tx, userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAmountByUserId indicates an expected call of GetAmountByUserId.
func (mr *MockwalletRepositoryMockRecorder) GetAmountByUserId(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAmountByUserId", reflect.TypeOf((*MockwalletRepository)(nil).GetAmountByUserId), ctx, tx, userID)
}

// SetAmount mocks base method.
func (m *MockwalletRepository) SetAmount(ctx context.Context, tx pgx.Tx, usesId, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAmount", ctx, tx, usesId, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAmount indicates an expected call of SetAmount.
func (mr *MockwalletRepositoryMockRecorder) SetAmount(ctx, tx, usesId, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAmount", reflect.TypeOf((*MockwalletRepository)(nil).SetAmount), ctx, tx, usesId, amount)
}

// StartTransaction mocks base method.
func (m *MockwalletRepository) StartTransaction(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockwalletRepositoryMockRecorder) StartTransaction(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockwalletRepository)(nil).StartTransaction), ctx)
}
